### ISSUE TITLE
How exactly does connection to linux ssh work? 

### ISSUE THREAD

**Issue by ArtiomLiakh** [DeathVenom54/discord-terminal#1]
Sorry, but I can't figure out where to place the ssh key for the bot to send commands to the right machine.

**Comment by 0xDevansh** [comment]
Hey there. This project does not use ssh keys at all. It is supposed to be run on the target machine only, and it will execute commands there.

In hindsight, this is a very stupid idea for security, but it is what it is...

**Comment by ArtiomLiakh** [comment]
Thanks!
